# Generated by Django 2.1.7 on 2019-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('virtualmachine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmware.VirtualMachine')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('moid', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='vcenter',
            name='port',
            field=models.CharField(default=443, max_length=20),
        ),
        migrations.CreateModel(
            name='ComputeResource',
            fields=[
                ('objectvm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vmware.ObjectVM')),
                ('is_cluster', models.BooleanField()),
                ('ha', models.NullBooleanField()),
                ('drs', models.NullBooleanField()),
            ],
            bases=('vmware.objectvm',),
        ),
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('objectvm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vmware.ObjectVM')),
                ('type', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=200)),
            ],
            bases=('vmware.objectvm',),
        ),
        migrations.CreateModel(
            name='HostSystem',
            fields=[
                ('objectvm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vmware.ObjectVM')),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmware.ComputeResource')),
                ('datastore', models.ManyToManyField(to='vmware.Datastore')),
            ],
            bases=('vmware.objectvm',),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('objectvm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vmware.ObjectVM')),
                ('net', models.GenericIPAddressField(protocol='ipv4')),
                ('netmask', models.PositiveSmallIntegerField(default=24)),
                ('accessible', models.BooleanField(default=True)),
            ],
            bases=('vmware.objectvm',),
        ),
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('objectvm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vmware.ObjectVM')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmware.ComputeResource')),
            ],
            bases=('vmware.objectvm',),
        ),
        migrations.AddField(
            model_name='objectvm',
            name='vcenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmware.Vcenter'),
        ),
        migrations.AddField(
            model_name='ipusage',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmware.Network'),
        ),
        migrations.AddField(
            model_name='hostsystem',
            name='network',
            field=models.ManyToManyField(to='vmware.Network'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='datastore',
            field=models.ManyToManyField(to='vmware.Datastore'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='hostsystem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmware.HostSystem'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='network',
            field=models.ManyToManyField(to='vmware.Network'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='resourcepool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmware.ResourcePool'),
        ),
    ]
