# Generated by Django 2.1.7 on 2019-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=50)),
                ('script_file', models.FileField(upload_to='~/script/')),
                ('script_args', models.TextField(blank=True, null=True)),
                ('script_type', models.CharField(max_length=50)),
            ],
        ),
    ]
