# Generated by Django 2.1.7 on 2019-03-23 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='script_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='script_args',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='script_file',
            field=models.TextField(),
        ),
    ]
